#!/bin/bash
#
# Quick reference for k3s deployment management
#

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           k3s Deployment Management Guide                        ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "🔧 REDEPLOY OPTIONS:"
echo ""
echo "1️⃣  SOFT REDEPLOY (make k3s-restart)"
echo "   Command: make k3s-restart"
echo "   What it does:"
echo "     ✓ Restarts all pods (rolling restart)"
echo "     ✓ Keeps all data in databases"
echo "     ✓ Keeps all configurations"
echo "     ✓ Zero downtime for most services"
echo "   Use when: Applying config changes, code updates"
echo "   Time: ~10-20 seconds"
echo ""
echo "2️⃣  HARD REDEPLOY (make k3s-redeploy → option 2)"
echo "   Command: make k3s-redeploy"
echo "   What it does:"
echo "     ✓ Deletes all app deployments"
echo "     ✓ Keeps infrastructure (DB, Redis, RabbitMQ)"
echo "     ✓ Keeps Docker images (no rebuild needed)"
echo "     ✓ Re-deploys from existing images"
echo "   Use when: Full application reset needed"
echo "   Time: ~30-60 seconds"
echo ""
echo "3️⃣  FULL RESET (make k3s-redeploy → option 3 / make k3s-clean)"
echo "   Command: make k3s-clean"
echo "   What it does:"
echo "     ✓ Deletes entire namespace"
echo "     ✓ Deletes ALL data (DBs empty)"
echo "     ✓ Keeps Docker images in k3s"
echo "     ✓ Need to re-import images"
echo "     ✓ Need full re-deploy"
echo "   Use when: Complete fresh start"
echo "   Time: ~2-5 minutes (setup + build + deploy)"
echo ""
echo "📋 QUICK COMMANDS:"
echo ""
echo "Restart only (keep everything):"
echo "  make k3s-restart"
echo ""
echo "Redeploy apps (keep DB data):"
echo "  make k3s-redeploy → choose option 2"
echo ""
echo "Full cleanup (start from scratch):"
echo "  make k3s-clean"
echo "  ./setup.sh"
echo ""
echo "💡 TIPS:"
echo "• Docker images stay in k3s even after full cleanup"
echo "• Only need to rebuild images if code changes"
echo "• Database data persists in Hard Redeploy"
echo "• Use Soft Redeploy for quick config updates"
echo ""
