package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/microservices-go/gateway/internal/user"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input user.RegisterInput) (*user.AuthResponse, error) {
	return r.UserClient.Register(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input user.LoginInput) (*user.AuthResponse, error) {
	return r.UserClient.Login(ctx, input)
}
