package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/microservices-go/gateway/graph/generated"
	"github.com/microservices-go/gateway/graph/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	me, err := r.Query().Me(ctx)
	if err != nil {
		return nil, err
	}
	return r.OrderClient.CreateOrder(ctx, input, me.ID)
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status string) (*model.Order, error) {
	return r.OrderClient.UpdateStatus(ctx, id, status)
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	loaders := GetLoaders(ctx)
	return loaders.UserLoader.Load(ctx, obj.UserID)
}

// ShippingAddress is the resolver for the shippingAddress field.
func (r *orderResolver) ShippingAddress(ctx context.Context, obj *model.Order) (string, error) {
	return obj.ShippingAddress, nil
}

// Payment is the resolver for the payment field.
func (r *orderResolver) Payment(ctx context.Context, obj *model.Order) (*model.Payment, error) {
	loaders := GetLoaders(ctx)
	return loaders.PaymentLoader.LoadByOrder(ctx, obj.ID)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	loaders := GetLoaders(ctx)
	return loaders.OrderLoader.LoadByID(ctx, id)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, limit *int, offset *int) (*model.OrderConnection, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.OrderClient.ListOrders(ctx, l, o)
}

// MyOrders is the resolver for the myOrders field.
func (r *queryResolver) MyOrders(ctx context.Context, limit *int, offset *int) (*model.OrderConnection, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.OrderClient.ListMyOrders(ctx, l, o)
}

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

type orderResolver struct{ *Resolver }
