package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/microservices-go/gateway/graph/generated"
	"github.com/microservices-go/gateway/internal/order"
	"github.com/microservices-go/gateway/internal/payment"
	"github.com/microservices-go/gateway/internal/user"
)

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, input payment.CreatePaymentInput) (*payment.Payment, error) {
	me, err := r.Query().Me(ctx)
	if err != nil {
		return nil, err
	}
	return r.PaymentClient.CreatePayment(ctx, input, me.ID)
}

// ProcessPayment is the resolver for the processPayment field.
func (r *mutationResolver) ProcessPayment(ctx context.Context, id string) (*payment.Payment, error) {
	return r.PaymentClient.ProcessPayment(ctx, id)
}

// RefundPayment is the resolver for the refundPayment field.
func (r *mutationResolver) RefundPayment(ctx context.Context, id string, amount *float64, reason *string) (*payment.Payment, error) {
	return r.PaymentClient.RefundPayment(ctx, id, amount, reason)
}

// Order is the resolver for the order field.
func (r *paymentResolver) Order(ctx context.Context, obj *payment.Payment) (*order.Order, error) {
	loaders := GetLoaders(ctx)
	return loaders.OrderLoader.LoadByID(ctx, obj.OrderID)
}

// User is the resolver for the user field.
func (r *paymentResolver) User(ctx context.Context, obj *payment.Payment) (*user.User, error) {
	loaders := GetLoaders(ctx)
	return loaders.UserLoader.Load(ctx, obj.UserID)
}

// Payment is the resolver for the payment field.
func (r *queryResolver) Payment(ctx context.Context, id string) (*payment.Payment, error) {
	loaders := GetLoaders(ctx)
	return loaders.PaymentLoader.LoadByID(ctx, id)
}

// PaymentByOrder is the resolver for the paymentByOrder field.
func (r *queryResolver) PaymentByOrder(ctx context.Context, orderID string) (*payment.Payment, error) {
	loaders := GetLoaders(ctx)
	return loaders.PaymentLoader.LoadByOrder(ctx, orderID)
}

// Payments is the resolver for the payments field.
func (r *queryResolver) Payments(ctx context.Context, limit *int, offset *int) (*payment.PaymentConnection, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.PaymentClient.ListPayments(ctx, l, o)
}

// MyPayments is the resolver for the myPayments field.
func (r *queryResolver) MyPayments(ctx context.Context, limit *int, offset *int) (*payment.PaymentConnection, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.PaymentClient.ListMyPayments(ctx, l, o)
}

// Payment returns generated.PaymentResolver implementation.
func (r *Resolver) Payment() generated.PaymentResolver { return &paymentResolver{r} }

type paymentResolver struct{ *Resolver }
