package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/microservices-go/gateway/graph/generated"
	"github.com/microservices-go/gateway/internal/order"
	"github.com/microservices-go/gateway/internal/user"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, firstName *string, lastName *string, isActive *bool) (*user.User, error) {
	return r.UserClient.UpdateUser(ctx, id, firstName, lastName, isActive)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	return r.UserClient.DeleteUser(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	return r.UserClient.Me(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*user.User, error) {
	loaders := GetLoaders(ctx)
	thunk := loaders.UserLoader.Load(ctx, id)
	return thunk()
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) (*user.UserConnection, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	return r.UserClient.ListUsers(ctx, l, o)
}

// Orders is the resolver for the orders field.
func (r *userResolver) Orders(ctx context.Context, obj *user.User, limit *int, offset *int) ([]*order.Order, error) {
	l := 10
	o := 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	// Use OrderClient directly for list queries (DataLoader is for single entity lookups)
	return r.OrderClient.GetOrdersByUser(ctx, obj.ID, l, o)
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
